### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'py_sk_embs'

### ISSUE THREAD

**Issue by DeerEyre** [Zhouyuhao97/PLOME_finetune_pytorch#5]
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    train.trainer(model, train_data_loader, test_data_loader, args, device, label_list, py_label_list)
  File "/code/PLOME_finetune_pytorch-main/train.py", line 42, in trainer
    prob_hanzi, prob_pinyin, _ = model(input_ids, pinyin_ids, stroke_ids, device, None, input_mask, True)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/code/PLOME_finetune_pytorch-main/model.py", line 98, in forward
    embedding_output = self.model.embeddings(input_ids=input_ids, position_ids=position_ids, py_sk_embs=py_sk_embs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'py_sk_embs'

我将模型转换成pytorch模式后 运行main.py遇到了这个错误

**Comment by DeerEyre** [comment]
没事了   是本地的transformer包与作者自己修改的transformers包冲突了  辛苦啦大家
